### PR TITLE
Feature/uh201 home page

### PR DESCRIPTION
**Pull request by ndelarans**
**feat(UH201):** Creation of the homepage. The website's homepage was developed to attract users, including the existing header and footer. The central content is divided into three sections: promotional images of discounted products, a grid of 12 featured products, and an advertising banner near the footer

**Desktop view**
destokp1
image
image
image
image

**Mobile view**

image
image
image
image
image

### CODE REVIEW

**Comment by sebastian0327** [comment]
looks great

**Review by sebastian0327 — APPROVED** [review]

**Comment by AlejandroSalas1143** [comment]
I see everything well

**Review by AlejandroSalas1143 — APPROVED** [review]

**Review by sebastian0327 — APPROVED** [review]

**Review by dgop92 — CHANGES_REQUESTED** [review]
Everything looks ok and the landing page is above my expectations, nevertheless, why do we have two body tags in the project?

image

**Review by dgop92 — APPROVED** [review]
Looks ok

**Pull request merged**
